import { GridData } from './grid-data';

//export const GRID_DATA: GridData[] = [
//  { text: "Oh" },
//  { text: "how" },
//  { text: "lovely" },
//  { text: "was" },
//  { text: "days" },
//  { text: "widows" },
//  { text: "Godhead" },
//  { text: "donkey", selected: true, locked: true },
//  { text: "never" },
//  { text: "be" },
//  { text: "ye" },
//  { text: "doers" },
//  { text: "to" },
//  { text: "golden" },
//  { text: "idols" },
//  { text: "vigor" },
//  { text: "be" },
//  { text: "forgotten" },
//  { text: "knock" },
//  { text: "and" },
//  { text: "Joseph's" },
//  { text: "martyrdom" },
//  { text: "gone" },
//  { text: "door" },
//  { text: "I" },
//  { text: "stand" },
//  { text: "at" },
//  { text: "the" },

//  //2
//  { text: "the" },
//  { text: "morning" },
//  { text: "covered" },
//  { text: "let" },
//  { text: "love" },
//  { text: "wisdom" },
//  { text: "wagons" },
//  { text: "windows" },
//  { text: "Only" },
//  { text: "Begotten" },
//  { text: "Son" },
//  { text: "flesh" },
//  { text: "work" },
//  { text: "done" },
//  { text: "agony" },
//  { text: "Sodom" },
//  { text: "ask" },
//  { text: "godly" },
//  { text: "sorrow" },
//  { text: "forgot" },
//  { text: "no" },
//  { text: "golden" },
//  { text: "idols" },
//  { text: "goodly" },
//  { text: "graven" },
//  { text: "images" },
//  { text: "born" },
//  { text: "of" },


//  //3
//  { text: "him" },
//  { text: "ask" },
//  { text: "of" },
//  { text: "Lamb" },  
//  { text: "of" },
//  { text: "kingdom" },
//  { text: "God" },
//  { text: "doeth" },
//  { text: "heaven" },
//  { text: "Holy" },
//  { text: "Ghost" },
//  { text: "dove" },  
//  { text: "and" },
//  { text: "Gomorrah" },
//  { text: "gospel" },
//  { text: "allegory" },
//  { text: "great" },
//  { text: "power" },
//  { text: "of" },
//  { text: "godliness" },
//  { text: "parents" },
//  { text: "Goliath" },
//  { text: "endowment" },
//  { text: "goat", selected: true, locked: true },
//  { text: "heavenly" },
//  { text: "David" },
//  { text: "repent" },
//  { text: "joy" }


//]

export const GRID_DATA: GridData[][] = [
  [
    { text: "Oh" },
    { text: "how" },
    { text: "lovely" },
    { text: "was" },
    { text: "the" },
    { text: "morning" },
    { text: "covered" },
    { text: "let" },
    { text: "him" },
    { text: "ask" },
    { text: "of" },
    { text: "Lamb" },
    { text: "will" },
  ],
  [
    { text: "days" },
    { text: "widows" },
    { text: "Godhead" },
    { text: "donkey", selected: true, locked: true },
    { text: "love" },
    { text: "wisdom" },
    { text: "wagons" },
    { text: "windows" },
    { text: "of" },
    { text: "kingdom" },
    { text: "God" },
    { text: "doeth" },
    { text: "the" },
  ],
  [
    { text: "never" },
    { text: "be" },
    { text: "ye" },
    { text: "doers" },
    { text: "Only" },
    { text: "Begotten" },
    { text: "Son" },
    { text: "flesh" },
    { text: "heaven" },
    { text: "Holy" },
    { text: "Ghost" },
    { text: "dove" },
    { text: "thanks" }
  ],
  [
    { text: "to" },
    { text: "golden" },
    { text: "idols" },
    { text: "vigor" },
    { text: "work" },
    { text: "done" },
    { text: "agony" },
    { text: "Sodom" },
    { text: "and" },
    { text: "Gomorrah" },
    { text: "gospel" },
    { text: "allegory" },
    { text: "olive" }
  ],
  [
    { text: "be" },
    { text: "forgotten" },
    { text: "knock" },
    { text: "and" },
    { text: "ask" },
    { text: "godly" },
    { text: "sorrow" },
    { text: "forgot" },
    { text: "great" },
    { text: "power" },
    { text: "of" },
    { text: "godliness" },
    { text: "tree" }
  ],
  [
    { text: "Joseph's" },
    { text: "martyrdom" },
    { text: "gone" },
    { text: "door" },
    { text: "no" },
    { text: "golden" },
    { text: "idols" },
    { text: "goodly" },
    { text: "parents" },
    { text: "Goliath" },
    { text: "endowment" },
    { text: "goat", selected: true, locked: true },
    { text: "pride" }
  ],
  [
    { text: "I" },
    { text: "stand" },
    { text: "at" },
    { text: "the" },
    { text: "graven" },
    { text: "images" },
    { text: "born" },
    { text: "of" },
    { text: "heavenly" },
    { text: "David" },
    { text: "repent" },
    { text: "joy" },
    { text: "prophet" }
  ]

]
